name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  compute-versions:
    runs-on: ubuntu-22.04
    outputs:
      latest: ${{ fromJson(steps.versions.outputs.latest) }}
      versions: ${{ steps.versions.outputs.versions }}
    concurrency:
      group: compute-versions${{ github.workflow }}${{ matrix.os }}${{ github.event.number || github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.1
      - name: Compute zstd versions
        id: versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          QUERY="$(./print-zstd-versions.sh)"
          echo "versions=$QUERY" >> $GITHUB_OUTPUT
          echo "latest=$(echo $QUERY | jq -c 'first')" >> $GITHUB_OUTPUT
  build:
    needs:
      - compute-versions
    strategy:
      matrix:
        zstd: ${{ fromJson(needs.compute-versions.outputs.versions) }}
        include:
          - zstd: ${{ needs.compute-versions.outputs.latest }}
            latest: true
    runs-on: ubuntu-22.04
    concurrency:
      group: build${{ github.workflow }}${{ matrix.zstd }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.1
      - name: Build Image
        run: docker build . -t danysk/zstd:${{ matrix.zstd }} --build-arg ZSTD_VERSION=${{ matrix.zstd }}
      - name: Add "latest" tag
        if: ${{ matrix.latest }}
        run: docker tag danysk/zstd:${{ matrix.zstd }} danysk/zstd:latest
      - name: Push to DockerHub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: danysk
        if: >-
          !github.event.repository.fork
          && (
            github.event_name != 'pull_request'
            || github.event.pull_request.head.repo.full_name == github.repository
          )
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
          docker push --all-tags danysk/zstd
  success:
    runs-on: ubuntu-22.04
    needs:
      - build
      - compute-versions
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
  # These lines are meant for renovate to trigger updates
  # This way, we don't set up a cronjob, which GitHub actions has the abit to disable in a while
  # requiring manuale intervention.
  trick-updates-as-cron:
    runs-on: ubuntu-22.04
    container: eclipse-temurin:18
    if: false
    steps:
      - uses: facebook/zstd@v1.5.5
